# -*- coding: utf-8 -*-
"""Analise_Exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FtKvaERmnNLU8vgziydgozMAB_0ElQJn
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('datasets\AdventureWorks.xlsx')

df.head(10)

df.dtypes

#Qual a receita total?
df["Valor Venda"].sum()

df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head()

round(df["Custo"].sum(), 2)

df["Lucro"] = df["Valor Venda"] - df["Custo"]

round(df["Lucro"].sum(), 2)

df["Tempo Envio"] = df["Data Envio"] - df["Data Venda"]

df.head()

df["Tempo Envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df["Tempo Envio"].dtype

df.groupby("Marca")["Tempo Envio"].mean()

df.isnull().sum()

df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

pd.options.display.float_format = "{:20,.2f}".format

lucro_ano = df.groupby([df["Data Venda"].dt.year,  "Marca"])["Lucro"].sum().reset_index()

lucro_ano

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Produto x Quantidade", color="dimgray");
plt.xlabel("Total")
plt.ylabel("Produto")

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro X Ano", color="dimgray");

df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title = "Lucro X Mês");

df_2009.groupby("Marca")["Lucro"].sum().sort_values(ascending=True).plot.barh(title = "Lucro X Marca")

df["Tempo Envio"].describe()

plt.boxplot(df["Tempo Envio"]);

plt.hist(df["Tempo Envio"]);

df[df["Tempo Envio"] == 20]

df.to_csv("df_vendas.csv", index=False)



"""# Nova seção"""